### ISSUE TITLE
mediawiki.api.parse is deprecated

### ISSUE THREAD

**Issue by Krinkle** [SemanticMediaWiki/SemanticCite#70]
FYI:

The mw.Api parse method(s) are part of the `mediawiki.api` module bundle as of <s>MW 1.31</s> MW 1.32, leaving `mediawiki.api.parse` as deprecated alias, to be removed in MW 1.33.

(Found via [Codesearch](https://codesearch.wmflabs.org/).)

**Comment by kghbln** [comment]
Thanks for reporting!

**Comment by kghbln** [comment]
In contrast to the original report the alias was only added in [MW 1.32.](https://phabricator.wikimedia.org/T196802#5435748)
> - In MW 1.31 and earlier, methods like `mw.Api#parse` existed in `mediawiki.api.parse`.
> - In MW 1.32, these were merged into `mediawiki.api`. With `mediawiki.api.parse` as alias. Using either works on this release, and one should migrate toward `mediawiki.api`.
> - In MW 1.33, the deprecated aliases were removed, and `mediawiki.api` must be used instead.

This means that we have to revert all respective changes. Is the same way of resolving this keeping the module until we no longer support MW 1.31 and later and drop it as soon as we switch to MW 1.35 as minimum support.

@mwjames @JeroenDeDauw Since I am not a programmer. What happens with MW 1.33 and 1.34 were we still have the module? Will this cause pain, meaning that we have to add some shim for compatibility.

**Comment by bescheid** [comment]
I just installed SMW cite 2.1.0 on a MW1.31.1. Everthing seems OK but js.tooltips do not work. The console reports: 

> VM5333:239 Uncaught TypeError: api.parse is not a function

See an example at https://www.univie.ac.at/rel_jap/an/Sandkiste2/SCI_example

**Comment by JeroenDeDauw** [comment]
Your MW version is too new for Semantic Cite

**Comment by bescheid** [comment]
Thank you... Any clue for a workaround?

**Comment by kghbln** [comment]
Fixed with #71 which will ship with SCI 2.1.1
